### PR TITLE
input validation and related tests

### PR DESCRIPTION
**Pull request by tyfranklin**
Definitions are now validated for type prior to loading endpoints (we may also want to check values). Currently, type checks and mock def models are limited. I suspect they'll need to be expanded later.

### CODE REVIEW

**Comment by jonathana** [comment]
Sorry it's taken me a while to get back to this.  There are some changes you made in her that are clearly more "node-like", converting my thrown errors to passing the error in as first argument to the callback provided.   I'm curious about your opinion, though, about the reason I used the pattern I did versus the stock node callback style (it was intentional on my part).  I'm trying to make sure that one can't build up a misconfigured server.  If you pass in an invalid configuration, I don't want the server to start up at all.  Can you think of either a cleaner, or more node-like way that you'd expect to see that versus the throw I used?

I'm aware users could stills subvert this by catching the unhandled exception and choosing to continue, but I'd like to make it clear that one would have to use bad style to get past a configuration problem.

Thoughts?

**Comment by tyfranklin** [comment]
Sure thing, and no prob. Re: the Node convention, I'm no guru on this front. My understanding is that we don't throw in async code for the reasons mentioned in [this thread](https://groups.google.com/d/msg/nodejs/W9UVJCKcJ7Q/rzseRbourCUJ). 

If I understand correctly, we want to stop the server setup when the endpoint definitions are wrong. If so, we'd likely _prefer_ the user do this (as opposed to us having to crash the process). They could choose to continue their setup or fail out depending on what they get back. But you're right, the user could just ignore us and hobble forward w/ their setup.

What if we put more input validation in the sync portion of our code and threw there? Alternatively, we could make our whole process synchronous. Pretty sure either would work. What do you think?

**Comment by jonathana** [comment]
I went ahead and merged this.  Your statement "we'd likely _prefer" the user to do this..." is actually counter-argument to what I'm saying.  I wouldn't prefer the user to do it, I want to make it _HARD_ for the user to do it.  They shouldn't be choosing to continue setup if the configuration is wrong.  I'm aware that this is counter to the "standard philosophy", but we're helping people build (hopefully) stable, secure services.  Presenting them the choice to continue in the face of identifying a known issue would run counter to that, wouldn't it?  Even if we're then going against the "standard behavior" expected of node libraries.

We can go back and address the mechanics of ensuring sane configuration later.  Making sure we're on a synchronous code path may be the way to go, but I still think maybe the process should die with an unhandled exception (or the user intentionally has to write a handler to address the misconfiguration and realizes that might not be the right thing) if the setup is not right.

**Comment by tyfranklin** [comment]
Sure thing, whichever you prefer. If I were trying to achieve the behavior you described, I'd likely try glob.sync and throw first. 

Let me know what you decide -- should have a few hours this Saturday and can implement then (or work on another piece).

**Comment by jonathana** [comment]
One thing to work on, which is my bad (an oversight on my part) in the spec I gave you.  Right now, the endpoint has to be a string.  Can you change the validation to allow either a string _or_ a regex?  Restify allows either, and I forgot the regex case.

**Pull request merged**
